version: '3.8'

services:
  backend:
    build:
      context: ./blockchain-microservice
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=${PORT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_PROJECT_NUMBER=${GCP_PROJECT_NUMBER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - ADMIN_PRIVATE_KEY=${ADMIN_PRIVATE_KEY}
      - NODE_URL=${NODE_URL}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
    volumes:
      - ./solargauge-66f76767c6a9.json:/app/solargauge-66f76767c6a9.json
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

  miner:
    # Definición del servicio para tu nodo minero
    build:
      context: ./red-crypto # Ruta donde está el Dockerfile del nodo
      dockerfile: Dockerfile # Asegúrate de que sea el Dockerfile correcto
    ports:
      - "8545:8545"
    command: [ "sh", "-c", "/red-crypto/start-node1.sh" ] #[ "sh", "-c", "tail -f /dev/null" ]

    networks:
      - app-network

volumes:
  postgres_data: {}

networks:
  app-network:
    driver: bridge
